baseURL: "https://malanjp.github.io"
languageCode: "ja-jp"
defaultContentLanguage: "ja"
title: "Malan"
paginate: 5
theme: "PaperMod"
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
hasCJKLanguage: true # If Chinese/Japanese/Korean is your main content language, enable this to make wordCount works right.
rssLimit: 10 # Maximum number of items in the RSS feed.
# googleAnalytics = "UA-123-45"

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  author: "malan"
  DateFormat: "2006-01-02 15:04 MST"
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Malan
    subtitle: "I'm Software Engineer at Tokyo/Japan."
    imageUrl: "/apple-touch-icon.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: malan
    buttons:
      - name: Blog
        url: https://malan.hatenablog.com/

  # home-info mode
  homeInfoParams:
    Title: "Malan"
    Content: "I'm Software Engineer at Tokyo/Japan."

  socialIcons:
    - name: twitter
      url: "https://twitter.com/ma1anjp"
    - name: github
      url: "https://github.com/malanjp"
    - name: twitch
      url: "https://twitch.tv/malanjp"
    - name: youtube
      url: "https://www.youtube.com/@malanjp"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/malanjp/malanjp.github.io/blob/main/content"
    Text: "Edit" # edit text
    appendFilePath: true # to append file path to Edit link

  outputs:
    home:
      - HTML
      - RSS
      - JSON # is necessary


  # # for search
  # # https://fusejs.io/api/options.html
  # fuseOpts:
  #   isCaseSensitive: false
  #   shouldSort: true
  #   location: 0
  #   distance: 1000
  #   threshold: 0.4
  #   minMatchCharLength: 0
  #   keys: ["title", "permalink", "summary", "content"]
  # title: "Search" # in any language you want
  # layout: "search" # is necessary
  # # url: "/archive"
  # # description: "Description for Search"
  # summary: "search"
# menu:
#   main:
#     - identifier: archives
#       name: Archives
#       url: /archives/
#       weight: 1
#     # - identifier: search
#     #   name: Search
#     #   url: /search/
#     #   weight: 10
#     - identifier: tags
#       name: Tags
#       url: /tags/
#       weight: 20
